name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Add your details in a MD text block under the letter of your country in a CountryName.md file'
        pr-message: 'You details will be submitted for the Alien overlords to browse'
